[package]
name = "seqrs"
description = "Fast statistics and filtering for FASTQ/FASTA files"
readme = "README.md"
keywords = ["fastq", "bio"]
version = "1.0.0"
authors = ["Rui Wang"]
edition = "2024"


[dependencies]
kseq = "0.5"
bio = "3"
clap = { version = "4", features = ["derive"] }
regex = "1"
rayon = "1.10"
indicatif = "0.17"
plotters = { version = "0.3", default-features = false, features = ["svg_backend", "line_series"] }
ferris-says = "0.3"
rand = "0.9"

[dev-dependencies]
assert_cmd = "2.1"
predicates = "3.1"